### ISSUE TITLE
Controller Item Selection Doesn't Work on Playstation with R1/L1

### ISSUE THREAD

**Issue by fiziaque** [RyanLua/Satchel#31]
### Description

Bug with R1/L1 selection of tool in the demo place, it tools are preloaded in the hotbar and you try to navigate through the hotbar, nothing happens, only when you have put everything into the inventory and transfer the tool from the inventory onto the hotbar does it work. Hope you figure out what causes this. I have tested on playstation

(L1 / R1 ) Are the left and right bumpers on the playstation controller

### Expected behavior

I expect R1/L1 tool navigation to work with controller on console even if tools have been preloaded.

### Actual behavior

Cannot navigate through hotbar when tools are already there. i.e preloaded or have been inside startergear. However tool navigation on controller works when you put all tools in inventory and transfer them back to hotbar.

### Steps to reproduce

1. Join demo place (the playground)
2. without opening inventory press r1/l1, try selecting tool, navigating through hotbar
3. put all hotbar tool in inventory
4. put some tools from inventory back to hotbar
5. should be working now

### Other details

This is quite an annoying bug and I hope this will be fixed as many controller/console players will experience this bug.

When you transfer it all to inventory and back to hotbar it is a temporary fix, as soon as you die/reset, you are unable to navigate through hotbar again until you repeat the process of transferring hotbar tools to inventory and back to hotbar.

### Version

v2.9.1

### Severity

Critical

### Platforms affected

Console

### Distribution variant

GitHub

### Code of Conduct

- [X] I have read and agree to the project's [Code of Conduct](../blob/main/CODE_OF_CONDUCT.md)

**Comment by RyanLua** [comment]
I've been unable to reproduce the issue with my Xbox Wireless Controller even when emulating PlayStation input from Xbox controller.

* Is this issue occurring using only PlayStation controllers?
* Can you reproduce this using different platforms? (Controller connected to phone, computer, etc.)
* Is there a place file in which you can consistently reproduce? If so, can you attach that?
* Are there any errors in the console?

In the version you specify you have v2.9.1 which isn't a valid distribution of Satchel as the latest is v1.2.0. Could you correct that to the version you are using?

**Comment by Fossahaque** [comment]
I am using the latest version, basically it doesn't work on console, I have tested using the playstation 4 version of roblox and this error occurs all the time, however I have tested the same playstation controller on my computer and it works flawlessly. 

I think this has to do something with the gamepad detections not working on console, maybe?

The place file is just the original satchel demo place.

I cannot access console for errors on playstation.

**Comment by Fossahaque** [comment]
It seems that changeToolFunc, runs once only when the player loads into the game and somehow unbinds it, that's why on I cannot use r1/l1 navigation on ps4, I still haven't figured out why it causes this to happen on playstation console but not on pc with playstation controller.

**Comment by RyanLua** [comment]
> It seems that changeToolFunc, runs once only when the player loads into the game and somehow unbinds it, that's why on I cannot use r1/l1 navigation on ps4, I still haven't figured out why it causes this to happen on playstation console but not on pc with playstation controller.

That is indeed odd. I tried looking at the code that handles changeToolFunc but wasn't able to spot anything off that would make the issue platform specific. It might take a while to solve this issue because I can't reproduce or properly isolate the issue.

Does this issue happen with Xbox consoles too or is it only PlayStation?

**Comment by RyanLua** [comment]
Hey, it seems like this is a bug with Roblox rather than Satchel. It looks like PlayStation 4 inputs are bugged on Roblox so they are not properly binding.

I am actively tracking this bug and will update this thread once the bug is resolved and Satchel is updated.

https://devforum.roblox.com/t/2760435
