### ISSUE TITLE
Default Hotbar showing

### ISSUE THREAD

**Issue by TheTechnologyStudio** [RyanLua/Satchel#79]
### Description

I installed the script into StarterPlayerScripts and removed the section for TopBarPlus and changed the line of code for icon Top Bar Plus to my own: local Icon: any = require(replicatedStorage.Storage.Modular_Scripts.Icon)
but it is not removing the default UI, It is showing Double Toolbars, Yours and the original Roblox One 

There are no errors in console.

![image](https://github.com/user-attachments/assets/dd4bd643-b9a4-4116-94df-ddb1732c27fc)

### Severity

High

### Platforms affected

Computer

### Distribution variant

Roblox Developer Forum

### Code of Conduct

- [X] I have read and agree to the project's [Code of Conduct](https://github.com/RyanLua/Satchel?tab=coc-ov-file)

**Comment by RyanLua** [comment]
Do any of your scripts attempt to enable the default backpack? 

Satchel will attempt to disable the default backpack but if another script enables it, it can't really do much. 

```lua
game.StarterGui:SetCoreGuiEnabled(Enum.CoreGuiType.Backpack, true)
```

**Comment by RyanLua** [comment]
Since I can’t reproduce this bug and haven’t received a response, I’ll assume that it’s an issue on your end and not a bug with Satchel. 

Feel free to reopen this issue if you feel like this is incorrect.
